### ISSUE TITLE
Update nbgv action to run on node 16

### ISSUE THREAD

**Issue by georg-jung** [dotnet/nbgv#53]
This action currently uses node 12, see https://github.com/dotnet/nbgv/blob/HEAD/action.yml#L84

Node 12 [is deprecated on GitHub Actions](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) since 2022-09-22.

When actions workflows that use the nbgv action run, we get the following warning message:
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: dotnet/nbgv`

**Comment by AArnott** [comment]
If you can confirm this fix works for you in the `master` branch, I'll merge the changes into the `v0.4` stable branch as well.

**Comment by georg-jung** [comment]
Indeed, changing

```diff
-    - uses: dotnet/nbgv@v0.4.0
+    - uses: dotnet/nbgv@master
```

resolves the warning regarding node 12 for us.

It also resolves a newer warning that just appeared recently:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by AArnott** [comment]
Thanks. I'll merge the changes into v0.4.
